@SistemaPenal_HostAddress = http://localhost:5034

### AUTENTICAÇÃO
POST {{SistemaPenal_HostAddress}}/auth/login
Content-Type: application/json

{
    "Email": "admin@sistemapenal.com",
    "Senha": "admin123"
}

### GET PRISIONEIRO CPF
GET {{SistemaPenal_HostAddress}}/prisioneiros/cpf/12345678900
Host: localhost:5034
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5Ac2lzdGVtYXBlbmFsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4MzQ5NzIyfQ._nKGVNK0h-adiYXh0coNahC1HbSOuA-BPLPr80ofQU8

### ANA: SE TIVER TESTANDO ONLY BACK, TROQUE O TOKEN DE CIMA PELO SEU!

POST {{SistemaPenal_HostAddress}}/dias-de-trabalho
Content-Type: application/json
Host: localhost:5034
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtaW5Ac2lzdGVtYXBlbmFsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzQ4MzUzMTY0fQ.0Q7IRZ7OFjoumxSo_Cz7jAK5BQUIASAbt3ruViABeeo

{
    "PrisioneiroId": "7c722e4c-8747-47a3-bdd2-ba5af72fccd2"
}